"""
One-time seed script to populate the `papers` table with Dr. Bora's existing
publication list (previously hardcoded in frontend/src/pages/Research.tsx).

Run once from the backend/ directory:
    python seed_papers.py

Safe to re-run: it skips seeding if the papers table already has rows.

NOTE ON PDFs: none of these entries get a pdf_url here. The original
frontend array pointed at placeholder paths (/papers/paper-N.pdf, mostly
files that don't exist) or, for a handful of entries, at PDFs manually
dropped into backend/uploads/paper/ without ever going through the
watermarking pipeline. Neither is safe to serve via the protected
/papers/{id}/pdf endpoint as-is. To attach a real, watermarked PDF to any
paper here, re-upload it through the admin paper create/update flow -
that runs it through add_watermark() and stores it the way
get_paper_pdf() expects.
"""

from database import SessionLocal, engine, Base
from models import Paper, PaperCategory, PaperScope

Base.metadata.create_all(bind=engine)

papers_data = [
    # -- BOOKS --
    dict(title="Asomor Chalachitrat Asomor Bastavata",
         journal="Tezpur University Publication Cell & CSTT, Ministry of Education, Govt. of India",
         institute="Tezpur University, Assam", co_author="Mr Debashis Pratim Sharma",
         isbn="978 81 968280 4 2", year="2025", category="Books", scope=None,
         abstract="This book examines the representation and reality of Assamese cinema, tracing how the regional film industry reflects and shapes the socio-cultural landscape of Assam."),
    dict(title="Radio - A True Medium of the Masses",
         journal="VDM Verlag, Germany", institute="VDM Verlag Dr. Müller, Germany",
         isbn="ISBN-13: 978-3639264487", year="2010", category="Books", scope=None,
         abstract="A study of radio broadcasting as a mass-reach medium, exploring its unique reach, accessibility, and continued relevance in an era of emerging digital media."),

    # -- PEER-REVIEWED JOURNAL PAPERS --
    dict(title="Jakarta Mahanagarit Satsari Ghatotkach", journal="Satsari (Monthly Assamese Magazine)",
         institute="Satsari Publications, Assam", volume="Vol. 19, Issue XI", issn="2319-8893 (UGCCARE)",
         year="June, 2024", category="Peer-Reviewed", scope="National",
         abstract="An account and analysis centered on events and observations in Jakarta, presented for an Assamese readership through the lens of the author's field experience."),
    dict(title="The continuities and changes in India's foreign policy", journal="Third Concept",
         institute="Third Concept Publications, Delhi", volume="Vol. 37, No. 435", issn="0970-7247",
         year="May, 2023", category="Peer-Reviewed", scope="National",
         abstract="This paper traces the evolution of India's foreign policy, identifying the ideological continuities that persist alongside the strategic changes shaped by shifting global dynamics."),
    dict(title="Coverage of India-related scientific news in western media: An analysis of the news portals of the New York Times and The Guardian",
         journal="Communicator", institute="Indian Institute of Mass Communication (IIMC), Delhi",
         volume="Vol. LVIII (1, 2)", issn="0588-8093 (UGCCARE)", year="January–June, 2023",
         category="Peer-Reviewed", scope="National",
         abstract="A comparative content analysis of how India-related scientific developments are framed and reported by two major Western news outlets, The New York Times and The Guardian."),
    dict(title="Assamese print media and freedom struggle – an insight (Co-Author)", journal="Communicator",
         institute="Indian Institute of Mass Communication (IIMC), Delhi", volume="Vol. LVII (1)",
         issn="0588-8093 (UGCCARE)", year="January–March, 2022", category="Peer-Reviewed", scope="National",
         abstract="This study revisits the role played by Assamese-language print media during India's freedom struggle, highlighting its contribution to mobilizing regional public opinion."),
    dict(title="New media and vernacular press: A study on the status of online vernacular journalism of Assam (Co-Author)",
         journal="Communicator", institute="Indian Institute of Mass Communication (IIMC), Delhi",
         volume="Vol. LVI (1)", issn="0588-8093 (UGCCARE)", year="January–March, 2021",
         category="Peer-Reviewed", scope="National",
         abstract="An examination of how vernacular journalism in Assam has adapted to online platforms, assessing the reach, credibility, and challenges of digital-first regional-language news."),
    dict(title="Cinema as a tool for health and risk communication: Issues and challenges",
         journal="Global Media Journal (India Edition)", institute="Global Media Journal, India",
         volume="Vol. 12, No. 2", issn="2249-5835 (UGCCARE)", year="December, 2020",
         category="Peer-Reviewed", scope="National",
         abstract="This paper explores cinema's potential as a vehicle for health and risk communication, along with the narrative and institutional challenges of using film for public messaging."),
    dict(title="Environment journalism in Assam: A study of two English dailies",
         journal="Indian Journal of Science Communication", institute="Indian Science Communication Society, Lucknow",
         volume="Vol. 19, No. 2", issn="0972-429X (UGCCARE)", year="July–December, 2020",
         category="Peer-Reviewed", scope="National",
         abstract="A comparative study of environmental reporting in two English-language dailies of Assam, evaluating the depth, frequency, and framing of ecological issues in regional coverage."),
    dict(title="Assamese cinema through nine decades: Challenging journey with encouraging trend (Principal Author)",
         journal="Global Media Journal (India Edition)", institute="Global Media Journal, India",
         volume="Vol. 12, No. 2", issn="2249-5835 (UGCCARE)", year="December, 2020",
         category="Peer-Reviewed", scope="National",
         abstract="A historical overview tracing nine decades of Assamese cinema, from its early struggles to its more recent creative and commercial resurgence."),
    dict(title="Health communication for COVID-19 and beyond: Exploring newer horizons",
         journal="Communicator", institute="Indian Institute of Mass Communication (IIMC), Delhi",
         volume="Vol. LV (1, 2)", issn="0588-8093 (UGCCARE)", year="January–June, 2020",
         category="Peer-Reviewed", scope="National",
         abstract="This paper studies the evolving strategies of health communication during the COVID-19 pandemic and proposes directions for more effective public health messaging going forward."),
    dict(title="Education during COVID-19 and beyond: Transition from face-to-face to Blended learning",
         journal="Vivekananda Journal of Research", institute="Vivekananda College, India",
         volume="Vol. 9, No. 2", issn="2456-7574", year="July–December, 2020",
         category="Peer-Reviewed", scope="National",
         abstract="An analysis of how educational institutions transitioned from traditional face-to-face instruction to blended learning models during the COVID-19 pandemic, and what lessons carry forward."),
    dict(title="Challenges of fake news: Mis-information, disinformation, malinformation in an increasingly-networked human world (Principal Author)",
         journal="Communicator", institute="Indian Institute of Mass Communication (IIMC), Delhi",
         volume="Vol. LIV (4)", issn="0588-8093 (UGCCARE)", year="October–December, 2019",
         category="Peer-Reviewed", scope="National",
         abstract="This paper unpacks the distinctions between misinformation, disinformation, and malinformation, examining the mounting challenges they pose in a densely networked information ecosystem."),
    dict(title="Media planning for communicating science", journal="Indian Journal of Science Communication",
         institute="Indian Science Communication Society, Lucknow", volume="Vol. 18, No. 2",
         issn="0972-429X (UGCCARE)", year="July–December, 2019", category="Peer-Reviewed", scope="National",
         abstract="A study on strategic media planning approaches suited to effective science communication, addressing audience segmentation, medium choice, and message design."),
    dict(title="Understanding Science communication in current context", journal="Indian Journal of Science Communication",
         institute="Indian Science Communication Society, Lucknow", volume="Vol. 17, No. 2",
         issn="0972-429X (UGCCARE)", year="July–December, 2017", category="Peer-Reviewed", scope="National",
         abstract="This paper revisits the scope and purpose of science communication, situating it within the contemporary media and public-engagement context."),
    dict(title="A post-modern idea of critical media literacy in the age of convergence (Co-Author)",
         journal="Global Media Journal (India Edition)", institute="Global Media Journal, India",
         issn="2249-5835 (UGCCARE)", year="2017", category="Peer-Reviewed", scope="National",
         abstract="An exploration of critical media literacy through a post-modern lens, considering how media convergence reshapes what it means to be a discerning media consumer."),
    dict(title="Grantharbhavishyat: Chapa granthaney e-book", journal="Gariyoshi",
         institute="Assam Tribune Publication House, Guwahati", volume="Vol. 13, No. 2",
         issn="2349-5324 (UGCCARE)", year="November, 2015", category="Peer-Reviewed", scope="National",
         abstract="A reflective piece on the future of the book, weighing the continued relevance of print publishing against the rise of e-books."),
    dict(title="Madhyam Swaksharata: Ak apariharjya praoyojan", journal="Gariyoshi",
         institute="Assam Tribune Publication House, Guwahati", volume="Vol. 22, No. 5",
         issn="2349-5324 (UGCCARE)", year="February, 2015", category="Peer-Reviewed", scope="National",
         abstract="This piece argues for media literacy as an indispensable skill for audiences navigating an increasingly complex and saturated media environment."),
    dict(title="Genre and sports films of Bollywood", journal="Journal of Research, Extension and Development",
         volume="Vol. 1, No. 11", issn="2319-1899", year="July, 2013", category="Peer-Reviewed", scope="National",
         abstract="A genre study of Bollywood sports films, examining the recurring narrative structures and thematic conventions that define the category."),
    dict(title="Nationalism in Bollywood sports films (Co-Author)",
         journal="International Journal of Research, Extension and Development", volume="Vol. 1, No. 2",
         issn="2321-3434", year="July–August, 2013", category="Peer-Reviewed", scope="National",
         abstract="This paper analyzes how nationalist themes are constructed and deployed in Bollywood sports films, and what this reveals about popular cinema's relationship with national identity."),
    dict(title="Media as a catalyst for higher education", journal="New Media and Mass Communication",
         institute="International Institute for Science and Technology and Education", volume="Vol. 2",
         issn="2224-3267 (Print)", year="2012", category="Peer-Reviewed", scope="International",
         abstract="This paper considers the catalytic role media can play in expanding access to, and improving the quality of, higher education."),
    dict(title="Media psychology: the need of the hour", journal="US-China Education Review",
         institute="David Publishing Company, USA", volume="Vol. 2, No. 10", issn="2161-6248",
         year="October, 2012", category="Peer-Reviewed", scope="International",
         abstract="An argument for greater integration of media psychology within communication studies, given its growing relevance to understanding audience behavior."),
    dict(title="Public service broadcasting by Radio: Challenges ahead", journal="Science Communicator",
         institute="Cochin University of Science and Technology, Kerala", volume="Vol. 3, Issue 2",
         issn="2231-217X", year="June, 2012", category="Peer-Reviewed", scope="National",
         abstract="An assessment of the structural and financial challenges facing public service radio broadcasting, and the reforms needed to sustain its mandate."),
    dict(title="Public Service Broadcasting by Radio: Challenges ahead", journal="New Media and Mass Communication",
         institute="International Institute of Science, Technology and Education", volume="Vol. 1",
         issn="2224-3267 (Print)", year="2011", category="Peer-Reviewed", scope="International",
         abstract="A companion study examining the operational and policy hurdles confronting public service radio broadcasting on an international stage."),
    dict(title="Community media for human development: Empowerment through the psychological route (Co-Author)",
         journal="Indian Journal of Health and Wellbeing", institute="Indian Association of Health, Research and Welfare",
         volume="Vol. 2, No. 4", issn="2229-5356", year="December, 2011", category="Peer-Reviewed", scope="National",
         abstract="This paper explores how community media contributes to human development by fostering psychological empowerment at the grassroots level."),
    dict(title="Psychology and media studies: Deriving the optimum benefit",
         journal="Indian Journal of Health and Wellbeing", institute="Indian Association of Health, Research and Welfare",
         volume="Vol. 2, No. 4", issn="2229-5356", year="December, 2011", category="Peer-Reviewed", scope="National",
         abstract="A discussion of the intersections between psychology and media studies, and how the two fields can be combined for mutual analytical benefit."),

    # -- REVIEWED (NON-PEER-REVIEWED) JOURNAL PAPERS --
    dict(title="Integrating Bharatiya Knowledge system in higher education for transmission of our culture and tradition",
         journal="University News (Special Issue)", institute="Association of Indian Universities, Delhi",
         volume="Vol. 61, No. 47", issn="0566-2257", year="November 22–26, 2023", category="Reviewed", scope="National",
         abstract="This paper proposes pathways for integrating the Bharatiya Knowledge System into higher education curricula as a means of preserving and transmitting cultural tradition."),
    dict(title="Mass communication education in India: Prospects and challenges", journal="University News",
         institute="Association of Indian Universities, Delhi", volume="Vol. 60, No. 34", issn="0566-2257",
         year="August 22–28, 2022", category="Reviewed", scope="National",
         abstract="A survey of the current state of mass communication education in India, weighing its future prospects against structural and curricular challenges."),
    dict(title="National Education Policy – 2020: The policy with futuristic vision", journal="University News",
         institute="Association of Indian Universities, Delhi", volume="Vol. 59, No. 7", issn="0566-2257",
         year="February 15–21, 2021", category="Reviewed", scope="National",
         abstract="This paper reviews the National Education Policy 2020, highlighting its forward-looking provisions and implications for the Indian education system."),
    dict(title="Communication and media: teaching and education – exploring the synergy",
         journal="Insight: Applied Research in Education", institute="Education Dept., Kashmir University, Srinagar",
         volume="Vol. 24, No. 1", year="2021", category="Reviewed", scope="National",
         abstract="An exploration of the synergy between communication studies and education, and how each field can inform pedagogical practice in the other."),
    dict(title="Community radio seeks that elusive boost", journal="Vidura", institute="Press Institute of India",
         volume="Vol. 5, No. 2", issn="0042-5303", year="April–June, 2013", category="Reviewed", scope="National",
         abstract="A commentary on the slow growth of community radio in India and the policy support it still needs to reach its full potential."),
    dict(title="ICT and Media in Open and Distance Learning: The need of the hour", journal="The Communications",
         institute="Directorate of Distance Education, University of Kashmir, Srinagar", volume="Vol. 21, No. 1",
         year="December, 2012", category="Reviewed", scope="National",
         abstract="This paper makes the case for greater use of ICT and media tools within open and distance learning systems to widen access to education."),
    dict(title="A few tenets of the US Mass media", journal="Vidura", institute="Press Institute of India",
         volume="Vol. 3, No. 1", issn="0042-5303", year="January–March, 2011", category="Reviewed", scope="National",
         abstract="An overview of key structural and cultural tenets that distinguish the mass media system of the United States."),
    dict(title="Make the right choice", journal="Vidura", institute="Press Institute of India", volume="Vol. 2, No. 3",
         issn="0042-5303", year="July–September, 2010", category="Reviewed", scope="National",
         abstract="A commentary piece reflecting on the choices facing media practitioners and consumers in a rapidly diversifying media landscape."),
    dict(title="Democratisation of information dissemination", journal="Vidura", institute="Press Institute of India",
         volume="Vol. 2, No. 1", issn="0042-5303", year="January–March, 2010", category="Reviewed", scope="National",
         abstract="This paper discusses how emerging media technologies have contributed to a broader democratisation of who can disseminate information."),
    dict(title="Mizoram – surjyodayar desh", journal="Payobhara", institute="Publication Division, Ministry of I&B, Delhi",
         issn="0971-8370", year="December, 2009", category="Reviewed", scope="National",
         abstract="A travel and culture piece introducing readers to Mizoram, framed as a land of the rising sun in the northeast."),
    dict(title="Samuhik anatar kendra: Jana savalikaranar adarsha madhyam", journal="Payobhara",
         institute="Publication Division, Ministry of I&B, Delhi", issn="0971-8370", year="November, 2009",
         category="Reviewed", scope="National",
         abstract="This piece presents community information centres as an ideal medium for grassroots public empowerment."),
    dict(title="Bharatat Gana Madhyamar Biplob", journal="Payobhara", institute="Publication Division, Ministry of I&B, Delhi",
         issn="0971-8370", year="May, 2009", category="Reviewed", scope="National",
         abstract="A discussion of the mass media revolution in India and its transformative impact on public communication."),
    dict(title="Going gaga over radio", journal="Vidura", institute="Press Institute of India", volume="Vol. 1, No. 2",
         issn="0042-5303", year="April–June, 2009", category="Reviewed", scope="National",
         abstract="A reflective piece on the resurgence of public enthusiasm for radio, examining what continues to draw audiences to the medium."),
    dict(title="Grahakei Raja", journal="Payobhara", institute="Publication Division, Ministry of I&B, Delhi",
         issn="0971-8370", year="February, 2009", category="Reviewed", scope="National",
         abstract="A commentary on consumer rights and the idea of the consumer as king within India's expanding marketplace."),
    dict(title="Tathyaprajukti – aparishim sambhavana aru uttar purvanchal", journal="Payobhara",
         institute="Publication Division, Ministry of I&B, Delhi", issn="0971-8370", year="November, 2007",
         category="Reviewed", scope="National",
         abstract="This paper explores the vast, largely untapped possibilities that information technology holds for development in India's northeast region."),
    dict(title="Ganamadhyamat jeevikar bishiyedu akhar", journal="NabaPragyan (Assamese Monthly)",
         institute="NabaPragyan Publications, Guwahati", volume="Vol. I, No. 6", year="September, 2006",
         category="Reviewed", scope="National",
         abstract="A piece considering mass media as a career path, laying out the opportunities and demands it presents for aspiring practitioners."),
    dict(title="Need for activist media audience", journal="Vidura", institute="Press Institute of India",
         volume="Vol. 43, No. 4", issn="0042-5303", year="October–December, 2006", category="Reviewed", scope="National",
         abstract="This paper argues for a more engaged, activist media audience that questions content rather than consuming it passively."),
    dict(title="Community radio to bridge gap", journal="Vidura", institute="Press Institute of India",
         volume="Vol. 43, No. 1", issn="0042-5303", year="October–December, 2006", category="Reviewed", scope="National",
         abstract="An examination of community radio's potential to bridge the information gap between mainstream media and underserved local communities."),
    dict(title="Kendriya ain sewa kartripaksha – vanchitajanar babey ashar batara", journal="Payobhara",
         institute="Publication Division, Ministry of I&B, Delhi", issn="0971-8370", year="January, 2006",
         category="Reviewed", scope="National",
         abstract="A piece on the Central Legal Services Authority and the hope it offers marginalised and underserved populations seeking access to justice."),
    dict(title="Mass communication as a meaningful career", journal="Pragyan (Quarterly Bilingual Journal)",
         institute="Tinsukia College, Tinsukia, Assam", volume="Vol. III, No. 1", year="September, 2005",
         category="Reviewed", scope="National",
         abstract="This paper discusses mass communication as a viable and meaningful career choice for students entering the field."),
    dict(title="Radio as a tool for social development", journal="Journal of GURSA",
         institute="Gauhati University Research Scholars' Association, Guwahati", volume="Vol. II", year="2005–06",
         category="Reviewed", scope="National",
         abstract="An examination of radio's role as a tool for driving social development, particularly in rural and underserved communities."),
    dict(title="Dangerous profession", journal="Vidura", institute="Press Institute of India", volume="Vol. 42, No. 4",
         issn="0042-5303", year="October–December, 2005", category="Reviewed", scope="National",
         abstract="A commentary on the risks and hazards journalists face in the course of their work, and what it means to call journalism a dangerous profession."),
    dict(title="Samuhik Anatar Kendra – Jana sablikaranar Adarsh amadhyam", journal="Deobaria Chora (Dainik Asom)",
         institute="Assam Tribune Publication Group, Guwahati", year="August 21, 2005", category="Reviewed", scope="National",
         abstract="This piece revisits community information centres as an ideal channel for grassroots public empowerment."),
    dict(title="Great leap for language press", journal="Vidura", institute="Press Institute of India",
         volume="Vol. 42, No. 2", issn="0042-5303", year="April–June, 2005", category="Reviewed", scope="National",
         abstract="A look at the significant growth and increasing influence of the regional-language press in India."),
    dict(title="Asom rajyik gramonnayan Pratishthan – bikashar batkatiya", journal="Payobhara",
         institute="Publication Division, Ministry of I&B, Delhi", issn="0971-8370", year="December, 2004",
         category="Reviewed", scope="National",
         abstract="A piece on the Assam State Rural Development Institute and its contribution to shaping the state's development trajectory."),
    dict(title="Uttar Purvanchal – Unnaayanar Abhimukhey", journal="Payobhara",
         institute="Publication Division, Ministry of I&B, Delhi", issn="0971-8370", year="October, 2004",
         category="Reviewed", scope="National",
         abstract="This paper looks at India's northeastern region and the direction of its ongoing development efforts."),
    dict(title="The need for community radio", journal="Vidura", institute="Press Institute of India",
         volume="Vol. 41, No. 4", issn="0042-5303", year="October–December, 2004", category="Reviewed", scope="National",
         abstract="An early call for the introduction and expansion of community radio as a means of localized, participatory broadcasting."),
    dict(title="SIRD-Guwahati – a role model for development", journal="Mirror of North-East (Fortnightly)",
         institute="Minakshi Publications, Guwahati", year="June 1–15, 2004", category="Reviewed", scope="National",
         abstract="A profile of the State Institute of Rural Development, Guwahati, presented as a model institution for regional development work."),
    dict(title="Atmasahayak got – gramyaunnayanar vikalpa path", journal="Prantik (Assamese Fortnightly)",
         institute="Prantik Publications, Guwahati", volume="Vol. 24, No. 1", year="December 1–15, 2004",
         category="Reviewed", scope="National",
         abstract="This piece presents self-help groups as an alternative pathway for rural development in Assam."),
    dict(title="Aksham lokar punarsansthapan aru vishessh shiksha", journal="Prantik (Assamese Fortnightly)",
         institute="Prantik Publications, Guwahati", volume="Vol. 23, No. 23", year="November 1–15, 2004",
         category="Reviewed", scope="National",
         abstract="A discussion of the rehabilitation and special education needs of persons with disabilities."),
    dict(title="Desh aru samajar sewat Rashtriya Shiskharthee Vahini", journal="Prantik (Assamese Fortnightly)",
         institute="Prantik Publications, Guwahati", volume="Vol. 23, No. 1", year="December 1–15, 2003",
         category="Reviewed", scope="National",
         abstract="This piece looks at the National Cadet Corps and its contribution to nation and community service."),
    dict(title="Tolaniya shishu – manavatar biral nidarshan", journal="Prantik (Assamese Fortnightly)",
         institute="Prantik Publications, Guwahati", volume="Vol. 22, No. 23", year="November 1–15, 2003",
         category="Reviewed", scope="National",
         abstract="A commentary on child labour, framed as a rare and troubling instance of human indifference."),
    dict(title="Assam Flying Club-r prati Radha Govinda Baruahdever avadan", journal="Prantik (Assamese Fortnightly)",
         institute="Prantik Publications, Guwahati", volume="Vol. 22, No. 6", year="February 16–28, 2003",
         category="Reviewed", scope="National",
         abstract="This piece documents Radha Govinda Baruah's contribution to the founding and growth of the Assam Flying Club."),

    # -- CONFERENCE PAPERS --
    dict(title="Science and Health Communication in Communication and Media Pedagogy of Higher Education Institutions: A case study of Assam (India) [Sole-cum-Main Author]",
         journal="Talk ASAP: Africa-Asia Pacific Dialogue on Communication Issues — 29th Annual Meet of AMIC, Manila",
         institute="AMIC, University of Padjajaran & FEU, Indonesia", venue="Bandung, Indonesia",
         year="September, 2023", category="Conference Papers", scope="International",
         abstract="A case study of higher education institutions in Assam, examining how science and health communication are integrated into communication and media pedagogy."),
    dict(title="The story of the coloured wall: Role of political wall graffiti in promoting party ideologies and influencing voting patterns in West Bengal (Co-Author with research scholar)",
         journal="29th Annual Meet of Asian Media Information and Communication Centre (AMIC), Manila",
         institute="AMIC, University of Padjajaran & FEU, Indonesia", venue="Bandung, Indonesia",
         year="September, 2023", category="Conference Papers", scope="International",
         abstract="This paper investigates political wall graffiti in West Bengal as a grassroots communication tool that shapes party ideology and influences voter behaviour."),
    dict(title="Ethics in Advertising: How to balance mass expectations and business interests",
         journal="International Conference on Interdisciplinary Business and Economics Research",
         institute="Society of Interdisciplinary Business Research (SIBR), Bangkok", venue="Bangkok, Thailand",
         year="June, 2013", category="Conference Papers", scope="International",
         abstract="This paper examines the ethical tensions in advertising between meeting public expectations and serving commercial business interests."),
    dict(title="Public service broadcasting in India: Not an encouraging scenario",
         journal="RadioAsia 2007: The future of Radio in the age of convergence",
         institute="AMIC & Asia-Pacific Broadcasting Union (ABU), Singapore", venue="Singapore",
         year="June, 2007", category="Conference Papers", scope="International",
         abstract="A critical assessment of public service broadcasting in India, arguing that the sector's condition remains discouraging despite its mandate."),

    # -- BOOK CHAPTERS --
    dict(title="Health Information Dissemination: Directions from COVID-19 and Thereafter",
         journal="Media in the time of COVID-19 (IIMC Dhenkanal Monograph 23)",
         institute="Indian Institute of Mass Communication, Dhenkanal", isbn="978 93 5407 738 8",
         year="June, 2020", category="Book Chapters", scope="National",
         abstract="This chapter draws directions for future health information dissemination based on lessons learned from media coverage during the COVID-19 pandemic."),
    dict(title="ODL in North-Eastern Region – Perspectives, and Challenges",
         journal="ODL: Issues and Perspectives – From East and North-East India (Edited Book)",
         institute="Krishna Kanta Handiqui State Open University, Guwahati & Netaji Subhash Open University, Kolkata",
         isbn="978 93 89559 64 4", year="December, 2019", category="Book Chapters", scope="National",
         abstract="This chapter surveys the perspectives and challenges surrounding open and distance learning across India's northeastern region."),
    dict(title="Media Literacy: Issues in Relevance", journal="Media in India: Parallels and Paradoxes (Edited Book)",
         institute="Bhupen Hazarika School of Mass Communication, KKHSOU, Guwahati", isbn="978 93 87940-45-1",
         year="January, 2019", category="Book Chapters", scope="National",
         abstract="This chapter interrogates the continued relevance of media literacy education amid India's rapidly diversifying media landscape."),
    dict(title="Reviewing Literature for C4D",
         journal="Decoding Communication for Development in India's North-East (Edited Book)",
         institute="ARMT South Asia, UNICEF-Assam & Gauhati University", isbn="978 81 933588 3 2",
         year="2019", category="Book Chapters", scope="National",
         abstract="A literature review chapter mapping the existing scholarship on Communication for Development as it applies to India's northeast."),
    dict(title="Radio – The Evergreen Medium", journal="Radio Journalism in India (Edited Book)",
         institute="Kanishka Publishers, Delhi", isbn="978 81 8457 798 3", year="2017",
         category="Book Chapters", scope="National",
         abstract="This chapter makes the case for radio's enduring relevance as an 'evergreen' medium even amid the rise of newer digital platforms."),
    dict(title="Why Development Journalism and Journalism Ethics",
         journal="Development Journalism: The Way Forward (Edited Book)",
         institute="Centre for Mass Communication, Rajasthan University & UNICEF, Jaipur", isbn="978 93 5265 664 6",
         year="2016", category="Book Chapters", scope="National",
         abstract="This chapter makes the case for development journalism grounded in strong ethical practice as a path forward for the profession."),
]


def seed():
    db = SessionLocal()
    try:
        if db.query(Paper).count() > 0:
            print("papers table already has rows - skipping seed "
                  "(delete rows first if you want to reseed).")
            return

        for p in papers_data:
            paper = Paper(
                title=p["title"],
                journal=p["journal"],
                institute=p.get("institute"),
                co_author=p.get("co_author"),
                volume=p.get("volume"),
                issn=p.get("issn"),
                isbn=p.get("isbn"),
                venue=p.get("venue"),
                year=p["year"],
                category=PaperCategory(p["category"]),
                scope=PaperScope(p["scope"]) if p.get("scope") else None,
                abstract=p.get("abstract"),
                pdf_url=None,
            )
            db.add(paper)

        db.commit()
        print(f"Seeded {len(papers_data)} papers.")
    finally:
        db.close()


if __name__ == "__main__":
    seed()